name: Pull Request - React Docker Build

on:
  pull_request:
    branches: [ "main" ]

jobs:
  pull-request-react:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build -t atlas-ui:test .
